In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

In [6]:
np

<module 'numpy' from '/usr/local/lib/python3.8/dist-packages/numpy/__init__.py'>

In [3]:
lst = [1, 2, 3]   # 1-dimension

In [4]:
lst

[1, 2, 3]

In [5]:
type(lst)

list

In [7]:
# to convert list to array
np.array(lst)

array([1, 2, 3])

In [8]:
arr = np.array(lst)
arr

array([1, 2, 3])

In [9]:
type(arr)   # n-dimensional array

numpy.ndarray

In [10]:
arr.ndim  # it is one dimensional array

1

In [11]:
lst1 = [[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7]]

In [19]:
lst1 = np.array(lst1)
arr = lst1

In [20]:
type(arr)

numpy.ndarray

In [21]:
arr.ndim      #2 dimensional array

2

In [22]:
# to check shape of the array (3 rows 3 column)
arr.shape

(3, 3)

In [23]:
arr.size  # how many elements in the array

9

In [24]:
# to check datatype of the array
arr.dtype

dtype('int64')

In [26]:
# function to generate zero values array
zeros = np.zeros((3,5))  # row-3, col-5  #have to use 2 bracket
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
ones = np.ones((6, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])