In [1]:
import numpy as np

In [2]:
# To generate random number from range(0-1)
np.random.random((3, 3))

array([[0.3979464 , 0.58962062, 0.06129038],
       [0.79210026, 0.89399671, 0.06766352],
       [0.07989568, 0.35841053, 0.40369343]])

In [3]:
np.random.random((3, 3))  # completely random numbers generated from range(0-1)

array([[0.10747477, 0.43123806, 0.31901636],
       [0.69255654, 0.48076737, 0.79047621],
       [0.58950799, 0.59577829, 0.78077478]])

In [4]:
np.random.random()

0.09932298459341027

In [7]:
if np.random.random() > 0.5:
  print("Run the function")
else:
  print("Don't run the function")

Run the function


In [8]:
np.arange(1, 10, 1)    # start-1 end-10 difference-1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1, 10, 3)

array([1, 4, 7])

In [10]:
np.linspace(1, 10, 10)     # start,end,how_many_values_I_want_in_between

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
np.linspace(1, 7, 10)   # i need value from (1-7) but 10 values (equivalance distance)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [12]:
arr = np.random.random((4, 3))   # 4 x 3 = 12
arr

array([[0.9010809 , 0.80755237, 0.61592281],
       [0.39173043, 0.94577497, 0.06416171],
       [0.97784655, 0.32522893, 0.60646283],
       [0.99701233, 0.46352538, 0.55290252]])

In [13]:
# to reshape the array
arr = np.reshape(arr, (3, 4))   # source, reshape to that format   # 3 x 4 = 12
arr

array([[0.9010809 , 0.80755237, 0.61592281, 0.39173043],
       [0.94577497, 0.06416171, 0.97784655, 0.32522893],
       [0.60646283, 0.99701233, 0.46352538, 0.55290252]])

In [14]:
arr = np.reshape(arr, (6,2))  # 6 x 2 = 12, shape must be the same in multiply
arr

array([[0.9010809 , 0.80755237],
       [0.61592281, 0.39173043],
       [0.94577497, 0.06416171],
       [0.97784655, 0.32522893],
       [0.60646283, 0.99701233],
       [0.46352538, 0.55290252]])

In [15]:
# flatten an array
arr.flatten()   # 2 dimensional array converted to 1 dimension

array([0.9010809 , 0.80755237, 0.61592281, 0.39173043, 0.94577497,
       0.06416171, 0.97784655, 0.32522893, 0.60646283, 0.99701233,
       0.46352538, 0.55290252])