In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [14]:
print(arr + 1)
print(arr - 1)
print(arr * 5)
print(arr / 2)
print(arr % 2)
print(arr ** 2)
print(arr ** 3)
print(arr // 2)

[2 3 4 5 6 7]
[0 1 2 3 4 5]
[ 5 10 15 20 25 30]
[0.5 1.  1.5 2.  2.5 3. ]
[1 0 1 0 1 0]
[ 1  4  9 16 25 36]
[  1   8  27  64 125 216]
[0 1 1 2 2 3]


In [13]:
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
arr = arr + 1
arr

array([2, 3, 4, 5, 6, 7])

In [16]:
arr += 1

In [17]:
arr

array([3, 4, 5, 6, 7, 8])

In [18]:
arr *= 2
arr

array([ 6,  8, 10, 12, 14, 16])

In [19]:
# to find maximum element in the array
arr.max()

16

In [20]:
# to find minimum element in the array
arr.min()

6

In case of multi-dimentional array

In [27]:
arr = np.array([[5, 4, 0], [3, 6, 8], [4, 9, 1]])

In [28]:
arr

array([[5, 4, 0],
       [3, 6, 8],
       [4, 9, 1]])

In [29]:
arr.max(axis=0)  # max element in column wise

array([5, 9, 8])

In [30]:
arr.max(axis=1)  # max element in row wise

array([5, 8, 9])

In [31]:
arr.min(axis=0)  # min element in column wise

array([3, 4, 0])

In [32]:
arr.min(axis=1)  # min element in row wise

array([0, 3, 1])

In [33]:
# sum of the all elements
arr.sum()

40