In [1]:
import numpy as np

In [8]:
arr1 = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

arr2 = np.array([[9, 8, 7],
                [6, 5, 4],
                [3, 2, 1]])

arr3 = np.array([[9, 8, 7, 5],
                 [6, 5, 4, 2],
                 [3, 2, 1, 5]])

In [9]:
arr1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [11]:
arr1 + arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [12]:
arr1 + arr2 + arr3

ValueError: ignored

In [ ]:
# dot product

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [13]:
arr1.dot(arr2)   # 1 x 9 + 2 x 6 + 3 x 3 = 9+12+9 = 30, 1 x 8 + 2 x 5 + 3 x 2 = 8+10+6 = 24

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [16]:
arr2.dot(arr1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

**How Indexing works on Array**



In [18]:
arr = np.array([1, 2, 3, 4, 5])

In [19]:
arr

array([1, 2, 3, 4, 5])

In [20]:
arr[:]

array([1, 2, 3, 4, 5])

In [21]:
arr[:3] # first 3 elements

array([1, 2, 3])

In [22]:
arr[:2] # first 2 elements

array([1, 2])

In [23]:
arr[2:]  # all the elements except first 2 elements

array([3, 4, 5])

In [24]:
arr[:-2] # all the elements except last two

array([1, 2, 3])

In [25]:
# In 2D Array

arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr1[:,:]   # to see all elements   # first one used for rows, second one for columns

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr1[:,:1] # all the rows but 1st column

array([[1],
       [4],
       [7]])

In [31]:
arr1[:1,:] # 1st row

array([[1, 2, 3]])

In [32]:
arr1[:2, :] # all the elements of first 2 rows

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr1[:,1:2] #to get the elements of only 2nd column

array([[2],
       [5],
       [8]])

In [35]:
arr1[1:2, 1:2]  # 2nd row, 2nd column

array([[5]])

In [36]:
arr1[1:, 1:] # all rows except 1st row and 1st column

array([[5, 6],
       [8, 9]])