In [1]:
import numpy as np

In [2]:
arr = np.array([[7, 3, 8, 6, 4],
         [7, 2, 9, 8, 6],
         [5, 4, 2, 3, 1]])

In [3]:
arr

array([[7, 3, 8, 6, 4],
       [7, 2, 9, 8, 6],
       [5, 4, 2, 3, 1]])

In [4]:
# sort row wise
np.sort(arr, axis=1, kind= 'mergesort')  # axis=1 is for column

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [5]:
# sort column wise
np.sort(arr, axis=0, kind= 'mergesort')  # axis=0 is for row

array([[5, 2, 2, 3, 1],
       [7, 3, 8, 6, 4],
       [7, 4, 9, 8, 6]])

In [6]:
# if not defined axis, it will sort row-wise
np.sort(arr, kind= 'mergesort')

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])