In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4],
                 [5,6,7,8]])
arr2 = np.array([[8,7,6,5],[4,3,2,1]])

In [3]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [5]:
# concinate arrays
# vertically - vstack
np.vstack((arr1, arr2))  # stack both array vertically

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [7]:
np.vstack((arr2, arr1))

array([[8, 7, 6, 5],
       [4, 3, 2, 1],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
# horizontally - hstack
np.hstack((arr1, arr2))  # horizontally stack

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [9]:
np.hstack((arr2, arr1))

array([[8, 7, 6, 5, 1, 2, 3, 4],
       [4, 3, 2, 1, 5, 6, 7, 8]])

In [13]:
arr = np.concatenate((arr1,arr2), axis=0)   # axis=0 vertically stack

In [11]:
np.concatenate((arr1,arr2), axis=1)  # horizontally stack

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [14]:
# split the array
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [16]:
# split horizontally
np.hsplit(arr, 2)  # source, to two arrays

[array([[1, 2],
        [5, 6],
        [8, 7],
        [4, 3]]), array([[3, 4],
        [7, 8],
        [6, 5],
        [2, 1]])]

In [17]:
# split vertically
np.vsplit(arr, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[8, 7, 6, 5],
        [4, 3, 2, 1]])]