In [1]:
import numpy as np

In [5]:
# 1D array

arr = ([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
# Indexing to access element
arr[1]

2

In [9]:
arr[ : ]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
arr[3 : ]

[4, 5, 6, 7, 8, 9]

In [11]:
arr[ : -3]

[1, 2, 3, 4, 5, 6]

In [12]:
arr[3: -3]

[4, 5, 6]

In [13]:
# 2D Array
arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [14]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [15]:
arr[ : , :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [16]:
arr[ :1, :] # access 1st row

array([[1, 2, 3, 4]])

In [17]:
arr[1: , :] # all rows except first row

array([[5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [18]:
arr[2 , :] # 2 means at index 2

array([8, 7, 6, 5])

In [20]:
arr[:, 1:] # all col except 1st

array([[2, 3, 4],
       [6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])

In [21]:
arr[:, 1:2]

array([[2],
       [6],
       [7],
       [3]])

In [22]:
arr[:, 1] # 1 means index 1 for col

array([2, 6, 7, 3])

In [23]:
arr[2, 3]  # index 2 row-wise, index 3 col-wise

5

In [24]:
# to crop the elements
arr[1 : , 1 : ]   # removing 1st row and 1st col

array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])