In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [9]:
q=0
for i in lst:
  if (i > 5):
    print(i)
    q+=1

print("Total elements : ")
print(q)

6
7
8
9
10
Total elements : 
5


In [5]:
# using numpy arrays
lst = np.array([1,2,3,4,5,6,7,8,9,10])

In [6]:
lst

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
lst > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [10]:
lst[lst > 5]

array([ 6,  7,  8,  9, 10])

In [11]:
len(lst[lst>5])

5

In [12]:
lst[lst%3 == 0]

array([3, 6, 9])